### ISSUE TITLE
waiting for spawn_reply indefinitely in rpc:multicall/5

### ISSUE THREAD

**Issue by zmstone** [erlang/otp#5346]
**Describe the bug**

`rpc:multicall/5` with `infinity` timeout got stuck waiting for `spawn_reply`

**To Reproduce**

It happened twice to us during load tests, but we are so far unable to find a minimal environment to reproduce.

**Expected behavior**

`spawn_request` should always send back `reply_tag`

**Affected versions**

Our test was done on OTP23.2.7.2

**Additional context**

The application code makes an `rpc:multicall`, towards 3 nodes, timeout=`infinity`
And gets stuck in states like below

```
process_info(<0.9.1000>, current_stacktrace).
{current_stacktrace,[{rpc,mc_spawn_replies,5,
                          [{file,"rpc.erl"},{line,833}]},
                     {rpc,multicall,5,[{file,"rpc.erl"},{line,774}]},
...
```

And the process has `DOWN` messages in its mailbox

```
process_info(<0.9.1000>, messages).          
{messages,[{'DOWN',#Ref<0.3171699583.3710648329.31880>,
                   process,<0.16590.952>,
                   {#Ref<0.3171699583.3710648329.31879>,return,
                    {true,['emqx@10.*.*.241']}}},
           {'DOWN',#Ref<0.3171699583.3710648329.31882>,process,
                   <60658.18472.957>,
                   {#Ref<0.3171699583.3710648329.31879>,return,
                    {true,['emqx@10.*.*.143']}}},
           {'DOWN',#Ref<0.3171699583.3710648329.31881>,process,
                   <60657.19060.942>,
                   {#Ref<0.3171699583.3710648329.31879>,return,
                    {true,['emqx@10.*.*.9']}}},
```

There were around 100K such processes as a result of a load test.

EDIT:
`{true,['emqx@10.*.*.241']}` is the 'normal' return value from the remote call (passed as a DOWN message to the caller).
meaning the remote call was successful, but for some reason `spawn_reply` was either not sent or lost.

**Comment by zmstone** [comment]
maybe the same as: https://github.com/erlang/otp/issues/4989

**Comment by zmstone** [comment]
With a timeout, we get `internal_error`.
```
{'EXIT',{{internal_error,[{rpc,mc_results,7,[{file,"rpc.erl"},{line,906}]},{rpc,multicall,5,[{file,"rpc.erl"},{line,776}]}, ...
```

**Comment by gorillainduction** [comment]
This looks like a bug in `rpc.erl`.

The code in rpc.erl is relying on the other side never crashing, and the other side is indeed always wrapping the execution in a catch. However, if the node connection goes down, this behavior will happen.

This is fixed in `erpc.erl` that was introduced in OTP 23.0, and under some circumstances the erpc code is used even from rpc, but not in the general case.

**Comment by rickard-green** [comment]
Thanks for the detailed bug report!

Yes, this is most likely the same bug as in #4989. It is very interesting that the bug seems to have triggered against all three nodes at the same time and that the spawns actually were successful. This crash gave much more information. I've gone through the code, but I'm still not able to find the bug. I'm planning to introduce some traps in the runtime system trying to get more information. Are you willing to run that in your load tests?

**Comment by zmstone** [comment]
Hi @rickard-green 
This was found in a test conducted in our customer's environment, so it's not very easy to run tests at-will.
But we are trying to reproduce it in our own environments too, we'll get back to you when we manage to reproduce.

**Comment by rickard-green** [comment]
@zmstone I've been able to reproduce it and found the bug. I'll soon make a pull request, but it might not be until the beginning of next week.

**Comment by rickard-green** [comment]
I've created PR #5355 which fixes the issue. It has just gone through some very basic testing yet, though.

The bug was that some distributed signals that needs to be forced into the distribution buffer even when it is marked as full were lost when the buffer was marked as full. Effected signals are EXIT signals due to links (with immediate exit reason), DOWN signals (with immediate exit reason), unlink acknowledgment signals, and spawn_reply signals.

The branch in the PR is based on the tip of the `maint-24` branch which you cannot use on the version you are at. You can find the branch `rickard/force-dist-signal-fix/23.2.7.2/GH-5346/GH-4989/OTP-17737` in [my git repository](https://github.com/rickard-green/otp) which contains the fix based on OTP 23.2.7.2. I would strongly recommend to upgrade to the tip of `maint-23` (currently at 23.3.4.8) though, since there are a lot of bug fixes that you do not have and wont get on the side branch `23.2.7.*`. You can also find the fix based on OTP 23.3.4.8 in the branch `rickard/force-dist-signal-fix/23.3.4.8/GH-5346/GH-4989/OTP-17737` (also in my repository).

I'm hoping to release patches for this on OTP 22, 23, and 24 later this week. Note that these patches will be released on the tips of the corresponding `maint-XY` branches (see [OTP Versions Tree](https://erlang.org/download/otp_versions_tree.html) for more info).

**Comment by rickard-green** [comment]
I just pushed to all of the above branches. The fix is the same as before, but I've added testcases and also added so that a node that detects the bug will log info about the bug being detected and also take down the connection to the buggy node. This will in the `rpc:multicall()` case cause it to return with failures against buggy nodes instead of just end up hanging. It is however only possible to detect the bug from a bug-free node in the special case when the bug has triggered on a `spawn_request()` with a monitor. The bug is detected upon the reception of the `DOWN` signal.

**Comment by rickard-green** [comment]
The fix has been released in the patch packages [OTP 24.1.5](https://erlang.org/download/OTP-24.1.5.README), [OTP 23.3.4.9](https://erlang.org/download/OTP-23.3.4.9.README), and [OTP 22.3.4.23](https://erlang.org/download/OTP-22.3.4.23.README) now.
