### ISSUE TITLE
25.0-rc1 Internal consistency check failed

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#5731]
**Describe the bug**
Compilation of https://github.com/CloudI/cloudi_core/ with rebar/rebar3 (or https://github.com/CloudI/CloudI/) fails with:
```
cloudi_core_i_configuration:1: function validate_aspects_f/4+14:
  Internal consistency check failed - please report this bug.
  Instruction: {call_only,4,{f,2665}}
  Error:       {bad_arg_type,
                   {x,1},
                   {t_cons,any,nil},
                   {t_list,
                       {t_union,none,none,none,
                           {t_tuple,2,true,#{}},
                           {t_fun,any,any,any}},
                       nil}}:
```

**To Reproduce**

    git clone https://github.com/CloudI/cloudi_core.git
    cd cloudi_core
    rebar get-deps
    rebar compile

**Expected behavior**
The compiler is able to compile.

**Affected versions**
`25.0-rc1`

**Comment by frej** [comment]
Not exactly the same `bad_arg_type`, but the following bugerl-reduced example triggers a validation-error:
```Erlang
-module(reduced).

-author('mjtruog at protonmail dot com').

-export([validate_aspects_f/3,
         services_validate_option_aspects_internal/9]).

validate_aspects_f([F | AspectsOld],
                   AspectsNew, Arity, AutomaticLoading)
    when is_function(F, Arity) ->
    validate_aspects_f(AspectsOld,
                       [F | AspectsNew],
                       Arity, AutomaticLoading).

validate_aspects_f(Aspects, Arity, AutomaticLoading) ->
    validate_aspects_f(Aspects, [], Arity, AutomaticLoading).

services_validate_option_aspects_internal(AspectsInitAfter,
                                          AspectsRequestBefore,
                                          AspectsRequestAfter,
                                          AspectsInfoBefore,
                                          AspectsInfoAfter,
                                          AspectsTerminateBefore,
                                          AspectsSuspend, AspectsResume,
                                          AutomaticLoading) ->
    ex:eval([{AspectsInitAfter,
              fun(Value) ->
                     services_validate_option_aspects_init_after_internal(Value,
                                                                          AutomaticLoading)
              end},
             {AspectsRequestBefore,
              fun(Value) ->
                     ex:services_validate_option_aspects_request_before_internal(Value,
                                                                                 AutomaticLoading)
              end},
             {AspectsRequestAfter,
              fun(Value) ->
                     ex:services_validate_option_aspects_request_after_internal(Value,
                                                                                AutomaticLoading)
              end},
             {AspectsInfoBefore,
              fun(Value) ->
                     ex:services_validate_option_aspects_info_before_internal(Value,
                                                                              AutomaticLoading)
              end},
             {AspectsInfoAfter,
              fun(Value) ->
                     ex:services_validate_option_aspects_info_after_internal(Value,
                                                                             AutomaticLoading)
              end},
             {AspectsTerminateBefore,
              fun(Value) ->
                     ex:services_validate_option_aspects_terminate_before(Value,
                                                                          AutomaticLoading)
              end},
             {AspectsSuspend,
              fun(Value) ->
                     ex:services_validate_option_aspects_suspend(Value,
                                                                 AutomaticLoading)
              end},
             {AspectsResume,
              fun(Value) ->
                     services_validate_option_aspects_resume(Value,
                                                             AutomaticLoading)
              end}]).

services_validate_option_aspects_init_after_internal(AspectsInit,
                                                     AutomaticLoading) ->
    case validate_aspects_f(AspectsInit, 5, AutomaticLoading) of
        {ok, _} = Success ->
            Success;
        {error, Entry} ->
            {error, {service_options_aspects_init_after_invalid, Entry}}
    end.

services_validate_option_aspects_resume(AspectsResume, AutomaticLoading) ->
    case validate_aspects_f(AspectsResume, 1, AutomaticLoading) of
        {ok, _} = Success ->
            Success;
        {error, Entry} ->
            {error, {service_options_aspects_resume_invalid, Entry}}
    end.

```

**Comment by frej** [comment]
Further reduction by hand gives:
```Erlang
-module(reduced).

-author('mjtruog at protonmail dot com').

-export([validate_aspects_f/3]).

validate_aspects_f([F | AspectsOld],
                   AspectsNew, Arity, AutomaticLoading)
    when is_function(F, Arity) ->
    validate_aspects_f(AspectsOld,
                       [F | AspectsNew],
                       Arity, AutomaticLoading).

validate_aspects_f(Aspects, Arity, AutomaticLoading) ->
    validate_aspects_f(Aspects, [], Arity, AutomaticLoading).

```

**Comment by bjorng** [comment]
I also reduced the module (by hand), but your version is somewhat smaller than mine. However, the `AutomaticLoading` parameter can be eliminated:

```
-module(reduced).
-export([validate_aspects_f/2]).

validate_aspects_f(Aspects, Arity) ->
    validate_aspects_f(Aspects, [], Arity).

validate_aspects_f([F | AspectsOld], AspectsNew, Arity) when is_function(F, Arity) ->
    validate_aspects_f(AspectsOld, [F | AspectsNew], Arity).
```

**Comment by frej** [comment]
>However, the AutomaticLoading parameter can be eliminated
Bugerl doesn't know how to drop parameters (yet?)

**Comment by jhogberg** [comment]
Thanks for your report, I've fixed it in https://github.com/erlang/otp/pull/5734

**Comment by jhogberg** [comment]
I've merged the fix now, thanks again for your report!

**Comment by okeuday** [comment]
@jhogberg Thanks for the fix in #5734 (commit https://github.com/erlang/otp/pull/5734/commits/383a444b4e16c90a038f4fd414e2ebcc6eeb2864).  However, when I attempt to use the master branch to avoid the failure it still occurs (did `update_primary` too).  Am I missing a special build step or is there still a problem?

**Comment by jhogberg** [comment]
There's another problem somewhere, I've reproduced it and I'm looking into it now. Sorry about that :-(

**Comment by jhogberg** [comment]
I forgot to update the `{test,is_function2, ...}` variant, so it worked for the minimized version but not the full one. Can you try this branch?

https://github.com/jhogberg/otp/tree/john/compiler/fix-is_function2-test

**Comment by jhogberg** [comment]
`Arity` is variable since it's a function argument (we don't inline unless asked to because you need to be able to trace it), but because the arguments are all constant we know that its range is between 1 and 12. This let the compiler select the cheaper `{test,is_function2,...}` instruction instead of `{bif,is_function2,...}` that https://github.com/erlang/otp/pull/5734 handled. I had forgotten that we use the former for variable arity too, so the validator couldn't follow what the optimization passes had done. :-(

Either way I've merged the branch above now, and I'm quite happy you spotted this as it's highlighted a minor quirk in how we translate guard BIFs to tests. Thanks again for your report!
